targets:
  $default:
    builders:
      dart_scope|_test_builder:
        generate_for:
          - test/dart_observable/observables/observable_combine_test.dart
          - test/dart_observable/states/states_computed_test.dart
          - test/dart_scope/configurables/computed_test.dart
builders:
  _test_builder:
    import: "test/test_gen/test_builder.dart"
    builder_factories: ["testBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
