targets:
  $default:
    builders:
      scopes|_test_builder:
        generate_for:
          - test/observables/observables/observable_combine_test.dart
          - test/observables/states/states_combine_test.dart
          - test/scopes/configurables/computed_test.dart
builders:
  _test_builder:
    import: "test/test_gen/test_builder.dart"
    builder_factories: ["testBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
