name: scopes
version: 0.1.0-alpha.1
homepage: https://github.com/LoveCommunity/scopes.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  typedef_foundation: ^0.1.0
  disposal: ^0.1.0-alpha.1


dev_dependencies:
  build: ^2.3.0
  build_runner: ^2.1.11
  source_gen: ^1.2.2
  test: ^1.17.12
